---
title: "Data preparation"
author: "Marina Papadopoulou"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data preparation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## 1.1 Load and transform data - trackdf

```{r message=FALSE, warning=FALSE}
library(swaRmverse)

raw <- read.csv(system.file("extdata/video/01.csv", package = "trackdf"))
raw <- raw[!raw$ignore, ]
raw$context <- c(rep('f', nrow(raw)/2 ), rep('u', nrow(raw)/2))
data_df <- set_data_format(raw_x = raw$x,
                          raw_y = raw$y,
                          raw_t = raw$frame,
                          raw_id = raw$id,
                          origin = "2019-03-24 12:55:23",
                          period = "1 sec",
                          tz = "America/New_York",
                        #  raw_track = raw$track
                          )

head(data_df)
```

Input parameters:
```{r message=FALSE, warning=FALSE}


```


## 1.2 Calculate pairwise and global metrics (Optional)


```{r message=FALSE, warning=FALSE}

data_dfs <- group_vels(data_df,
                       lonlat = FALSE,
                       verbose = T,
                       parallelize = T
                       )

smoothing_time_window <- 30 # seconds

g_metr <- group_global_metrics(data_list = data_dfs,
                               mov_av_time_window = smoothing_time_window,
                               lonlat = FALSE,
                               return_df = TRUE,
                               out_csv_dir = NA,
                               parallelize = F)

data_df <- group_nn_metrics(data_list = data_dfs,
                            lonlat = FALSE,
                            verbose = TRUE,
                            parallelize = FALSE)

```

## 1.3 Calculate metrics of collective motion

If step 2 is skipped, we calculate the metrics from the raw formatted data:
```{r message=FALSE, warning=FALSE}

smoothing_time_window <- 30 # seconds

new_species_metrics <- col_motion_metrics_from_raw(data_df,
                                mov_av_time_window = smoothing_time_window,
                                step2time = 1,
                                lonlat = FALSE,
                                verbose = TRUE,
                                interactive_mode = FALSE,
                                speed_lim = 5,
                                pol_lim = 0.3,
                                parallelize_all = FALSE
                                )

```
If we have already calculated the global and pairwise metrics we use them directly:

```{r message=FALSE, warning=FALSE}

new_species_metrics <- col_motion_metrics(data_df,
                                           global_metrics = g_metr,
                                           mov_av_time_window = 30,
                                           step2time = 1,
                                           verbose = TRUE,
                                           interactive_mode = FALSE,
                                           speed_lim = 5,
                                           pol_lim = 0.3
)

new_species_metrics$species <- "new_species_id"

#ev_sum <- events_summary(data_df, step2time = 1)

```
